// Package cmd wires together all gosim CLI commands.
package cmd

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/spf13/cobra"

	"github.com/Datto27/GOSim/internal/config"
	"github.com/Datto27/GOSim/internal/db"
	"github.com/Datto27/GOSim/internal/embeddings"
	"github.com/Datto27/GOSim/internal/store"
)

// configPath is the resolved path to the config file, populated by the
// --config flag (or DefaultConfigPath if the flag is not set).
var configPath string

// Context keys for values passed through Cobra's command context.
type (
	poolCtxKey    struct{}
	storeCtxKey   struct{}
	embedderCtxKey struct{}
)

func storeFromCtx(ctx context.Context) *store.Store {
	s, _ := ctx.Value(storeCtxKey{}).(*store.Store)
	return s
}

func embedderFromCtx(ctx context.Context) *embeddings.OllamaEmbedder {
	e, _ := ctx.Value(embedderCtxKey{}).(*embeddings.OllamaEmbedder)
	return e
}

func poolFromCtx(ctx context.Context) *pgxpool.Pool {
	p, _ := ctx.Value(poolCtxKey{}).(*pgxpool.Pool)
	return p
}

var rootCmd = &cobra.Command{
	Use:   "gosim",
	Short: "Universal semantic similarity search engine",
	Long: `gosim imports any collection of JSON objects, embeds them as vectors, and
finds the most similar items to any query. It detects each collection's
parameters and lets you weight them, so you control what "similar" means —
across collections too.

Run 'gosim setup' to get started.`,
	SilenceUsage:  true,
	SilenceErrors: true,
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		if skipConfigLoad(cmd) {
			return nil
		}

		// Resolve config path if not set by --config flag.
		if configPath == "" {
			p, err := config.DefaultConfigPath()
			if err != nil {
				return err
			}
			configPath = p
		}

		cfg, err := config.Load(configPath)
		if err != nil {
			return fmt.Errorf("%w\n\nRun 'gosim setup' to create a config file.", err)
		}
		ctx := config.WithContext(cmd.Context(), cfg)

		pool, err := db.Connect(ctx, cfg.DatabaseURL)
		if err != nil {
			return err
		}
		ctx = context.WithValue(ctx, poolCtxKey{}, pool)

		st := store.New(pool)
		ctx = context.WithValue(ctx, storeCtxKey{}, st)

		embedder := embeddings.New(cfg.OllamaURL, cfg.Model, cfg.Dimensions)
		ctx = context.WithValue(ctx, embedderCtxKey{}, embedder)

		if err := st.ValidateProfile(ctx, string(cfg.Profile)); err != nil {
			return err
		}

		cmd.SetContext(ctx)
		return nil
	},
	PersistentPostRunE: func(cmd *cobra.Command, args []string) error {
		if pool := poolFromCtx(cmd.Context()); pool != nil {
			pool.Close()
		}
		return nil
	},
}

// skipConfigLoad returns true for commands that must run before a config file
// exists (setup) or that are auto-generated by Cobra (help, completion).
func skipConfigLoad(cmd *cobra.Command) bool {
	// Annotation-based skip: set on commands explicitly.
	if cmd.Annotations["skipConfig"] == "true" {
		return true
	}
	// Cobra built-ins that don't have annotations.
	name := cmd.Name()
	if name == "help" || name == "completion" || name == "gosim" {
		return true
	}
	// Completion subcommands (bash, zsh, fish, powershell).
	if parent := cmd.Parent(); parent != nil && parent.Name() == "completion" {
		return true
	}
	return false
}

func init() {
	// --config flag on root, inherited by all subcommands.
	rootCmd.PersistentFlags().StringVar(
		&configPath, "config", "",
		"config file (default: ~/.config/gosim/config.json)",
	)

	rootCmd.AddCommand(
		setupCmd,
		doctorCmd,
		migrateCmd,
		importCmd,
		resetCmd,
		indexCmd,
		schemaCmd,
		weightsCmd,
		searchCmd,
		listCmd,
		statsCmd,
		infoCmd,
		serveCmd,
	)
}

// Execute is the single entry point called from main.
func Execute() error {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		return err
	}
	return nil
}
